#!/usr/bin/env bash
# Cloud Agent install: idempotent dependency + toolchain setup.
# Runs once to build the environment snapshot. Must terminate.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
log() { echo "[install] $*"; }

# --- JavaScript dependencies ------------------------------------------------
# Pin pnpm via corepack (package.json "packageManager") so the lockfile's
# overrides are honoured and installs stay deterministic.
log "Installing JS dependencies with pnpm"
corepack enable >/dev/null 2>&1 || sudo corepack enable
corepack prepare pnpm@10.33.3 --activate
pnpm install --frozen-lockfile

# --- System tooling for the local Supabase stack ---------------------------
if ! command -v docker >/dev/null 2>&1; then
	log "Installing Docker + fuse-overlayfs + iptables"
	sudo apt-get update -qq
	sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
		-o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold \
		docker.io docker-compose-v2 fuse-overlayfs uidmap iptables
fi

if ! command -v supabase >/dev/null 2>&1; then
	SUPABASE_VERSION="2.117.0"
	log "Installing Supabase CLI v${SUPABASE_VERSION}"
	tmp="$(mktemp -d)"
	curl -fsSL -o "$tmp/supabase.tar.gz" \
		"https://github.com/supabase/cli/releases/download/v${SUPABASE_VERSION}/supabase_linux_amd64.tar.gz"
	tar -xzf "$tmp/supabase.tar.gz" -C "$tmp"
	sudo mv "$tmp/supabase" /usr/local/bin/supabase
	rm -rf "$tmp"
fi

# Docker daemon configuration for nested Cloud Agent VMs:
#  - fuse-overlayfs storage driver (kernel overlay mounts are unavailable)
#  - legacy iptables backend (required for container-to-container networking)
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy >/dev/null 2>&1 || true
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy >/dev/null 2>&1 || true
sudo mkdir -p /etc/docker
printf '%s\n' '{
  "features": { "containerd-snapshotter": false },
  "storage-driver": "fuse-overlayfs"
}' | sudo tee /etc/docker/daemon.json >/dev/null

# --- Bring the stack up once to pull images + apply migrations -------------
# Bakes the Supabase images and the migrated database volume into the
# snapshot so future boots start quickly without re-downloading.
"$REPO_ROOT/.cursor/start.sh"

# --- Local development environment file ------------------------------------
if [ ! -f "$REPO_ROOT/.env.local" ]; then
	log "Generating .env.local for the local Supabase stack"
	# Deterministic local Supabase demo keys (safe for local development only).
	# shellcheck disable=SC2046
	export $(supabase status -o env 2>/dev/null | sed 's/"//g' | xargs -d '\n') || true
	vapid="$(node -e "const w=require('web-push');const k=w.generateVAPIDKeys();console.log(k.publicKey+' '+k.privateKey)")"
	vapid_public="${vapid%% *}"
	vapid_private="${vapid##* }"
	cat > "$REPO_ROOT/.env.local" <<EOF
# Local development env for Cloud Agent — points at the local Supabase stack.
# Generated by .cursor/install.sh. Safe for local development only.
NEXT_PUBLIC_SUPABASE_URL=${API_URL:-http://127.0.0.1:54321}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_URL=${API_URL:-http://127.0.0.1:54321}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
VAPID_EMAIL=mailto:dev@example.com
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${vapid_public}
VAPID_PRIVATE_KEY=${vapid_private}
API_SECRET=dev-api-secret
CRON_SECRET=dev-cron-secret
X_TWEET_DRY_RUN=true
X_POST_IMAGE_THEME=light
EOF
fi

log "Install complete"
